permissions:
  contents: write
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        # with:
        #   node-version: 18
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun i
          bun rss
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update RSS